### ISSUE TITLE
[WRATH] ComboPoints glitch

### ISSUE THREAD

**Issue by XyzKangUI** [Meorawr/LibFrameFade#3]
Your library causes the following issue described here: https://github.com/jordonwow/safequeue/issues/20

**Comment by Meorawr** [comment]
Going to take the lazy route here - the fundamental issue with UIFrameFade was fixed in Classic a _very_ long time ago, so the purpose of this library is a bit moot now.

cf7f8a5 (v5) resolves this issue by just disabling the functionality of the library in Classic clients.
