### ISSUE TITLE
LUA Error on startup:attempt to call method 'SetResetDisallowedIfNew'

### ISSUE THREAD

**Issue by alexandersoto** [Meorawr/LibFrameFade#4]
Hi there, there is an [issue](https://github.com/jordonwow/safequeue/issues/26) with [safequeue ](https://github.com/jordonwow/safequeue) but I think it's due to this library.

I'm seeing this error on startup:

```lua
22x SafeQueue/Libs/LibFrameFade/LibFrameFade.lua:39: attempt to call method 'SetResetDisallowedIfNew' (a nil value)
[string "@SafeQueue/Libs/LibFrameFade/LibFrameFade.lua"]:39: in function `OnLoad'
[string "@SafeQueue/Libs/LibFrameFade/LibFrameFade.lua"]:314: in main chunk

Locals:
self = Frame {
 closures = <table> {
 }
 faderPool = <table> {
 }
 hooks = <table> {
 }
}
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = true
(*temporary) = "attempt to call method 'SetResetDisallowedIfNew' (a nil value)"
```

**Comment by Meorawr** [comment]
Fixed on my end at least. To my knowledge the issue that SafeQueue fixes was resolved by Blizzard ~a year and a half ago, so you might just be able to disable the addon entirely and not run into any problems with blocked actions.
